spring:
  mail:
    host: smtp.163.com
    username: blog_data_system@163.com
    password: SBNEANQCRZRKXJWK
    default-encoding: UTF-8
    protocol: smtp
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000