name: build & push handleData-api docker images
 
on:   # 配置触发workflow的事件
  push:
    tags:       # tag更新时触发此workflow
      - '*'
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: BuildDockerImage
      run: docker build . --file handleData-api/dockerfile --tag betaincao/handle-data-api:${{ github.ref }}
    - name: Log into registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u betaincao --password-stdin
    - name: Push image
      run: docker push betaincao/handle-data-api:${{ github.ref }}
